"""invitations table.

Revision ID: 41122028d5a0
Revises: d8a5e407b546
Create Date: 2026-08-23 13:34:39.408087

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41122028d5a0"
down_revision: str | Sequence[str] | None = "d8a5e407b546"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitations_email"), "invitations", ["email"], unique=False)
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=False)
    # One active (unaccepted) Invitation per email (ADR 0012).
    op.create_index(
        "uq_invitations_email_active",
        "invitations",
        ["email"],
        unique=True,
        postgresql_where=sa.text("accepted_at IS NULL"),
    )
    # ### end Alembic commands ###

    # Project convention: every table gets an updated_at trigger (see .agents/skills/migrate).
    op.execute(
        "CREATE TRIGGER updated_at_trigger BEFORE UPDATE ON invitations "
        "FOR EACH ROW EXECUTE PROCEDURE before_update_updated_at();"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS updated_at_trigger ON invitations")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_invitations_email_active", table_name="invitations")
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_table("invitations")
    # ### end Alembic commands ###
