"""add insertion-order sequence to activity.

Revision ID: c0de8a243260
Revises: 41122028d5a0
Create Date: 2026-08-23 15:19:19.081695

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0de8a243260"
down_revision: str | Sequence[str] | None = "41122028d5a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add a monotonic insertion-order column to the append-only activity table.

    Rows written in one transaction share the same ``now()`` timestamp, so
    ``created_at`` alone cannot order an Issue's Activity feed.
    """
    op.execute("ALTER TABLE activity ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        """
        UPDATE activity AS a
        SET seq = o.n
        FROM (
            SELECT id, row_number() OVER (ORDER BY created_at, id) AS n
            FROM activity
        ) AS o
        WHERE a.id = o.id
        """
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('activity', 'seq'), "
        "COALESCE((SELECT MAX(seq) FROM activity), 0) + 1, false)"
    )


def downgrade() -> None:
    """Drop the activity seq column (its identity sequence drops with it)."""
    op.execute("ALTER TABLE activity DROP COLUMN seq")
