import uuid
from datetime import datetime
from typing import TYPE_CHECKING, ClassVar, Optional

from sqlalchemy import UUID, Column, DateTime, Text, text
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from core.models.user import User


class Activity(SQLModel, table=True):
    """Model Class Activity.

    Append-only audit row on an Issue (brief §2): who changed what, from → to.
    Written by the service layer only.

    The ``seq`` column (insertion order, migration c0de8a243260) is managed
    by the database and intentionally not mapped on this model; an
    autogenerated migration proposing ``op.drop_column("activity", "seq")``
    must be removed.
    """

    __tablename__: ClassVar[str] = "activity"

    id: uuid.UUID = Field(
        sa_column=Column(
            UUID,
            primary_key=True,
            server_default=text("gen_random_uuid()"),
        ),
        default_factory=uuid.uuid4,
    )
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            server_default=text("now()"),
            nullable=False,
        ),
        default_factory=datetime.now,
    )
    updated_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            server_default=text("now()"),
            onupdate=text("now()"),
            nullable=False,
        ),
        default_factory=datetime.now,
    )
    issue_id: uuid.UUID = Field(foreign_key="issues.id", nullable=False)
    actor_id: uuid.UUID | None = Field(default=None, foreign_key="users.id")
    kind: str = Field(max_length=50, nullable=False)
    field: str | None = Field(default=None, max_length=100)
    from_value: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    to_value: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    # Set on comment.* rows: which Comment the row is about (ticket 06).
    # No FK on purpose: a comment.deleted row outlives the Comment.
    comment_id: uuid.UUID | None = Field(default=None)

    actor: Optional["User"] = Relationship(
        sa_relationship_kwargs={"primaryjoin": "Activity.actor_id == User.id"}
    )
